-- MySQL Script generated by MySQL Workbench
-- Thu Dec 17 13:52:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema apipaulkamran
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `apipaulkamran` ;

-- -----------------------------------------------------
-- Schema apipaulkamran
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apipaulkamran` DEFAULT CHARACTER SET utf8 ;
USE `apipaulkamran` ;

-- -----------------------------------------------------
-- Table `apipaulkamran`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apipaulkamran`.`User` (
  `iduser` INT NOT NULL,
  `nom_user` VARCHAR(45) NOT NULL,
  `prenom_user` VARCHAR(45) NOT NULL,
  `email_user` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apipaulkamran`.`Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apipaulkamran`.`Image` (
  `idImage` INT NOT NULL,
  `nomimage` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idImage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apipaulkamran`.`Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apipaulkamran`.`Video` (
  `idVideo` INT NOT NULL,
  `nomvideo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVideo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apipaulkamran`.`Asset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apipaulkamran`.`Asset` (
  `idAsset` INT NOT NULL,
  `nomasset` VARCHAR(45) NOT NULL,
  `Image_idImage` INT NOT NULL,
  `Video_idVideo` INT NOT NULL,
  PRIMARY KEY (`idAsset`, `Image_idImage`, `Video_idVideo`),
  INDEX `fk_Asset_Image_idx` (`Image_idImage` ASC) VISIBLE,
  INDEX `fk_Asset_Video1_idx` (`Video_idVideo` ASC) VISIBLE,
  CONSTRAINT `fk_Asset_Image`
    FOREIGN KEY (`Image_idImage`)
    REFERENCES `apipaulkamran`.`Image` (`idImage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asset_Video1`
    FOREIGN KEY (`Video_idVideo`)
    REFERENCES `apipaulkamran`.`Video` (`idVideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apipaulkamran`.`groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apipaulkamran`.`groupe` (
  `idgroupe` INT NOT NULL,
  `nomgroupe` VARCHAR(45) NOT NULL,
  `Asset_idAsset` INT NOT NULL,
  `Asset_Image_idImage` INT NOT NULL,
  `Asset_Video_idVideo` INT NOT NULL,
  `User_iduser` INT NOT NULL,
  PRIMARY KEY (`idgroupe`),
  INDEX `fk_groupe_Asset1_idx` (`Asset_idAsset` ASC, `Asset_Image_idImage` ASC, `Asset_Video_idVideo` ASC) VISIBLE,
  INDEX `fk_groupe_User1_idx` (`User_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_groupe_Asset1`
    FOREIGN KEY (`Asset_idAsset` , `Asset_Image_idImage` , `Asset_Video_idVideo`)
    REFERENCES `apipaulkamran`.`Asset` (`idAsset` , `Image_idImage` , `Video_idVideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groupe_User1`
    FOREIGN KEY (`User_iduser`)
    REFERENCES `apipaulkamran`.`User` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apipaulkamran`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apipaulkamran`.`Message` (
  `id_emetteur` INT NOT NULL,
  `id_recepteur` INT NOT NULL,
  `Message` TEXT NOT NULL,
  PRIMARY KEY (`id_emetteur`, `id_recepteur`),
  INDEX `fk_User_has_User_User2_idx` (`id_recepteur` ASC) VISIBLE,
  INDEX `fk_User_has_User_User1_idx` (`id_emetteur` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_User_User1`
    FOREIGN KEY (`id_emetteur`)
    REFERENCES `apipaulkamran`.`User` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_User_User2`
    FOREIGN KEY (`id_recepteur`)
    REFERENCES `apipaulkamran`.`User` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
